// @ts-check

const Cast = require('../util/cast');
const StringUtil = require('../util/string-util');
const BlockType = require('../extension-support/block-type');
const Variable = require('../engine/variable');
const log = require('../util/log');
const {IntermediateScript, IntermediateRepresentation} = require('./intermediate');
const compatBlocks = require('./compat-blocks');

const {BLOCKS} = require('./enums');

// eslint-disable-next-line no-unused-vars
const Thread = require('../engine/thread.js');

/**
 * @typedef {import('./jsgen.js').node} node
 */

/**
 * @fileoverview Generate intermediate representations from Scratch blocks.
 */


const SCALAR_TYPE = '';
const LIST_TYPE = 'list';

/**
 * Create a variable codegen object.
 * @param {'target'|'stage'} scope The scope of this variable -- which object owns it.
 * @param {import('../engine/variable.js')} varObj The Scratch Variable
 * @returns {*} A variable codegen object.
 */
const createVariableData = (scope, varObj) => ({
    scope,
    id: varObj.id,
    name: varObj.name,
    isCloud: varObj.isCloud
});

/**
 * @param {string} code
 * @param {boolean} warp
 * @returns {string}
 */
const generateProcedureVariant = (code, warp) => {
    if (warp) {
        return `W${code}`;
    }
    return `Z${code}`;
};

/**
 * @param {string} variant Variant generated by generateProcedureVariant()
 * @returns {string} original procedure code
 */
const parseProcedureCode = variant => variant.substring(1);

/**
 * @param {string} variant Variant generated by generateProcedureVariant()
 * @returns {boolean} true if warp enabled
 */
const parseIsWarp = variant => variant.charAt(0) === 'W';

class ScriptTreeGenerator {
    /**
     * @param {Thread} thread
     */
    constructor (thread) {
        /** The main thread being compiled.
         * @private
         * @type {Thread}
         */
        this.thread = thread;
        /** @private */
        this.target = thread.target;
        /** @private */
        this.blocks = thread.blockContainer;
        /** @private */
        this.runtime = this.target.runtime;
        /** @private */
        this.stage = this.runtime.getTargetForStage();

        /**
         * This script's intermediate representation.
         */
        this.script = new IntermediateScript();
        this.script.warpTimer = this.target.runtime.compilerOptions.warpTimer;

        /**
         * Cache of variable ID to variable data object.
         * @type {Object.<string, object>}
         * @private
         */
        this.variableCache = {};

        this.usesTimer = false;
    }

    /**
     * @param {string} procedureVariant
     * @throws {Error} if the procedure cannot be found
     * @returns {void}
     */
    setProcedureVariant (procedureVariant) {
        const procedureCode = parseProcedureCode(procedureVariant);

        this.script.procedureVariant = procedureVariant;
        this.script.procedureCode = procedureCode;
        this.script.isProcedure = true;
        this.script.yields = false;

        const paramNamesIdsAndDefaults = this.blocks.getProcedureParamNamesIdsAndDefaults(procedureCode);
        if (paramNamesIdsAndDefaults === null) {
            throw new Error(`IR: cannot find procedure: ${procedureVariant}`);
        }

        const [paramNames, _paramIds, _paramDefaults] = paramNamesIdsAndDefaults;
        this.script.arguments = paramNames;
    }

    enableWarp () {
        this.script.isWarp = true;
    }

    /**
     * @param {string} blockId
     * @returns {any}
     */
    getBlockById (blockId) {
        // Flyout blocks are stored in a special container.
        return this.blocks.getBlock(blockId) || this.blocks.runtime.flyoutBlocks.getBlock(blockId);
    }

    /**
     * @param {string} fullOpcode
     * @returns {blockInfo|null}
     */
    getBlockInfo (fullOpcode) {
        const [category, opcode] = StringUtil.splitFirst(fullOpcode, '_');
        if (!category || !opcode) {
            return null;
        }
        const categoryInfo = this.runtime._blockInfo
            .find(/** @param {blockInfo} ci */ ci => ci.id === category);

        if (!categoryInfo) {
            return null;
        }
        const blockInfo = categoryInfo.blocks
            .find(/** @param {blockInfo} b */ b => b.info.opcode === opcode);

        if (!blockInfo) {
            return null;
        }
        return blockInfo;
    }

    /**
     * Descend into a child input of a block. (eg. the input STRING of "length of ( )")
     * @param {*} parentBlock The parent Scratch block that contains the input.
     * @param {string} inputName The name of the input to descend into.
     * @private
     * @returns {node} Compiled input node for this input.
     */
    descendInputOfBlock (parentBlock, inputName) {
        const input = parentBlock.inputs[inputName];
        if (!input) {
            log.warn(`IR: ${parentBlock.opcode}: missing input ${inputName}`, parentBlock);
            return {
                kind: BLOCKS.CONSTANT,
                value: 0
            };
        }
        const inputId = input.block;
        const block = this.getBlockById(inputId);
        if (!block) {
            log.warn(`IR: ${parentBlock.opcode}: could not find input ${inputName} with ID ${inputId}`);
            return {
                kind: BLOCKS.CONSTANT,
                value: 0
            };
        }

        return this.descendInput(block);
    }

    /**
     * Descend into an input. (eg. "length of ( )")
     * @param {*} block The parent Scratch block input.
     * @private
     * @returns {node} Compiled input node for this input.
     */
    descendInput (block) {
        switch (block.opcode) {
        case 'colour_picker':
            return {
                kind: BLOCKS.CONSTANT,
                value: block.fields.COLOUR.value
            };
        case 'math_angle':
        case 'math_integer':
        case 'math_number':
        case 'math_positive_number':
        case 'math_whole_number':
            return {
                kind: BLOCKS.CONSTANT,
                value: block.fields.NUM.value
            };
        case 'text':
            return {
                kind: BLOCKS.CONSTANT,
                value: block.fields.TEXT.value
            };

        case 'argument_reporter_string_number': {
            const name = block.fields.VALUE.value;
            // lastIndexOf because multiple parameters with the same name will use the value of the last definition
            const index = this.script.arguments.lastIndexOf(name);
            if (index === -1) {
                // Legacy support
                if (name.toLowerCase() === 'last key pressed') {
                    return {
                        kind: BLOCKS.TW.LAST_KEY_PRESSED
                    };
                }
            }
            if (index === -1) {
                return {
                    kind: BLOCKS.CONSTANT,
                    value: 0
                };
            }
            return {
                kind: BLOCKS.PROCEDURES.ARGUMENT,
                index: index
            };
        }
        case 'argument_reporter_boolean': {
            // see argument_reporter_string_number above
            const name = block.fields.VALUE.value;
            const index = this.script.arguments.lastIndexOf(name);
            if (index === -1) {
                /** @param {string} input */
                const normalizeValue = input => {
                    const lowered = String(input)
                        .toLowerCase()
                        .trim()
                        .replace(/\s+/g, ' ');
                    return lowered.endsWith('?') ? lowered.slice(0, -1).trim() : lowered;
                };

                const normalizedName = normalizeValue(name);
                if (normalizedName === 'is compiled' ||
                    normalizedName === 'is turbowarp' ||
                    normalizedName === 'is remixwarp') {
                    return {
                        kind: BLOCKS.CONSTANT,
                        value: true
                    };
                }
                return {
                    kind: BLOCKS.CONSTANT,
                    value: 0
                };
            }
            return {
                kind: BLOCKS.PROCEDURES.ARGUMENT,
                index: index
            };
        }

        case 'control_get_counter':
            return {
                kind: BLOCKS.COUNTER.GET
            };

        case 'data_variable':
            return {
                kind: BLOCKS.VAR.GET,
                variable: this.descendVariable(block, 'VARIABLE', SCALAR_TYPE)
            };
        case 'data_itemoflist':
            return {
                kind: BLOCKS.LIST.GET,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                index: this.descendInputOfBlock(block, 'INDEX')
            };
        case 'data_lengthoflist':
            return {
                kind: BLOCKS.LIST.LENGTH,
                list: this.descendVariable(block, 'LIST', LIST_TYPE)
            };
        case 'data_listcontainsitem':
            return {
                kind: BLOCKS.LIST.CONTAINS,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                item: this.descendInputOfBlock(block, 'ITEM')
            };
        case 'data_itemnumoflist':
            return {
                kind: BLOCKS.LIST.INDEXOF,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                item: this.descendInputOfBlock(block, 'ITEM')
            };
        case 'data_listcontents':
            return {
                kind: BLOCKS.LIST.CONTENTS,
                list: this.descendVariable(block, 'LIST', LIST_TYPE)
            };
        case 'data_get_list_as':
            return {
                kind: BLOCKS.LIST.AS,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                format: block.fields.FORMAT.value
            };
        case 'event_broadcast_menu': {
            const broadcastOption = block.fields.BROADCAST_OPTION;
            const broadcastVariable = this.target.lookupBroadcastMsg(broadcastOption.id, broadcastOption.value);
            // TODO: empty string probably isn't the correct fallback
            const broadcastName = broadcastVariable ? broadcastVariable.name : '';
            return {
                kind: BLOCKS.CONSTANT,
                value: broadcastName
            };
        }

        case 'looks_backdropnumbername':
            if (block.fields.NUMBER_NAME.value === 'number') {
                return {
                    kind: BLOCKS.LOOKS.BACKDROP_NUMBER
                };
            }
            return {
                kind: BLOCKS.LOOKS.BACKDROP_NAME
            };
        case 'looks_costumenumbername':
            if (block.fields.NUMBER_NAME.value === 'number') {
                return {
                    kind: BLOCKS.LOOKS.COSTUME_NUMBER
                };
            }
            return {
                kind: BLOCKS.LOOKS.COSTUME_NAME
            };
        case 'looks_costumes':
            return {
                kind: BLOCKS.LOOKS.COSTUMES
            };
        case 'looks_size':
            return {
                kind: BLOCKS.LOOKS.SIZE
            };

        case 'motion_direction':
            return {
                kind: BLOCKS.MOTION.DIRECTION
            };
        case 'motion_xposition':
            return {
                kind: BLOCKS.MOTION.X_POSITION
            };
        case 'motion_yposition':
            return {
                kind: BLOCKS.MOTION.Y_POSITION
            };

        case 'operator_add':
            return {
                kind: BLOCKS.OP.ADD,
                left: this.descendInputOfBlock(block, 'NUM1'),
                right: this.descendInputOfBlock(block, 'NUM2')
            };
        case 'operator_and':
            return {
                kind: BLOCKS.OP.AND,
                left: this.descendInputOfBlock(block, 'OPERAND1'),
                right: this.descendInputOfBlock(block, 'OPERAND2')
            };
        case 'operator_contains':
            return {
                kind: BLOCKS.OP.CONTAINS,
                string: this.descendInputOfBlock(block, 'STRING1'),
                contains: this.descendInputOfBlock(block, 'STRING2')
            };
        case 'operator_divide':
            return {
                kind: BLOCKS.OP.DIVIDE,
                left: this.descendInputOfBlock(block, 'NUM1'),
                right: this.descendInputOfBlock(block, 'NUM2')
            };
        case 'operator_equals':
            return {
                kind: BLOCKS.OP.EQUALS,
                left: this.descendInputOfBlock(block, 'OPERAND1'),
                right: this.descendInputOfBlock(block, 'OPERAND2')
            };
        case 'operator_gt':
            return {
                kind: BLOCKS.OP.GREATER,
                left: this.descendInputOfBlock(block, 'OPERAND1'),
                right: this.descendInputOfBlock(block, 'OPERAND2')
            };
        case 'operator_join':
            return {
                kind: BLOCKS.OP.JOIN,
                left: this.descendInputOfBlock(block, 'STRING1'),
                right: this.descendInputOfBlock(block, 'STRING2')
            };
        case 'operator_length':
            return {
                kind: BLOCKS.OP.LENGTH,
                string: this.descendInputOfBlock(block, 'STRING')
            };
        case 'operator_letter_of':
            return {
                kind: BLOCKS.OP.LETTEROF,
                letter: this.descendInputOfBlock(block, 'LETTER'),
                string: this.descendInputOfBlock(block, 'STRING')
            };
        case 'operator_lt':
            return {
                kind: BLOCKS.OP.LESS,
                left: this.descendInputOfBlock(block, 'OPERAND1'),
                right: this.descendInputOfBlock(block, 'OPERAND2')
            };
        case 'operator_mathop': {
            const value = this.descendInputOfBlock(block, 'NUM');
            const operator = block.fields.OPERATOR.value.toLowerCase();
            switch (operator) {
            case 'abs': return {
                kind: BLOCKS.OP.ABS,
                value
            };
            case 'floor': return {
                kind: BLOCKS.OP.FLOOR,
                value
            };
            case 'ceiling': return {
                kind: BLOCKS.OP.CEILING,
                value
            };
            case 'sqrt': return {
                kind: BLOCKS.OP.SQRT,
                value
            };
            case 'sin': return {
                kind: BLOCKS.OP.SIN,
                value
            };
            case 'cos': return {
                kind: BLOCKS.OP.COS,
                value
            };
            case 'tan': return {
                kind: BLOCKS.OP.TAN,
                value
            };
            case 'asin': return {
                kind: BLOCKS.OP.ASIN,
                value
            };
            case 'acos': return {
                kind: BLOCKS.OP.ACOS,
                value
            };
            case 'atan': return {
                kind: BLOCKS.OP.ATAN,
                value
            };
            case 'ln': return {
                kind: BLOCKS.OP.LN,
                value
            };
            case 'log': return {
                kind: BLOCKS.OP.LOG,
                value
            };
            case 'e ^': return {
                kind: BLOCKS.OP.EXP,
                value
            };
            case '10 ^': return {
                kind: BLOCKS.OP.TENEXP,
                value
            };
            default: return {
                kind: BLOCKS.CONSTANT,
                value: 0
            };
            }
        }
        case 'operator_mod':
            return {
                kind: BLOCKS.OP.MOD,
                left: this.descendInputOfBlock(block, 'NUM1'),
                right: this.descendInputOfBlock(block, 'NUM2')
            };
        case 'operator_pi':
            return {
                kind: BLOCKS.CONSTANT,
                value: Math.PI
            };
        case 'operator_newline':
            return {
                kind: BLOCKS.CONSTANT,
                value: '\n'
            };
        case 'operator_multiply':
            return {
                kind: BLOCKS.OP.MULTIPLY,
                left: this.descendInputOfBlock(block, 'NUM1'),
                right: this.descendInputOfBlock(block, 'NUM2')
            };
        case 'operator_not':
            return {
                kind: BLOCKS.OP.NOT,
                operand: this.descendInputOfBlock(block, 'OPERAND')
            };
        case 'operator_or':
            return {
                kind: BLOCKS.OP.OR,
                left: this.descendInputOfBlock(block, 'OPERAND1'),
                right: this.descendInputOfBlock(block, 'OPERAND2')
            };
        case 'operator_random': {
            const from = this.descendInputOfBlock(block, 'FROM');
            const to = this.descendInputOfBlock(block, 'TO');
            // If both values are known at compile time, we can do some optimizations.
            // TODO: move optimizations to jsgen?
            if (from.kind === BLOCKS.CONSTANT && to.kind === BLOCKS.CONSTANT) {
                const sFrom = from.value;
                const sTo = to.value;
                const nFrom = Cast.toNumber(sFrom);
                const nTo = Cast.toNumber(sTo);
                // If both numbers are the same, random is unnecessary.
                // todo: this probably never happens so consider removing
                if (nFrom === nTo) {
                    return {
                        kind: BLOCKS.CONSTANT,
                        value: nFrom
                    };
                }
                // If both are ints, hint this to the compiler
                if (Cast.isInt(sFrom) && Cast.isInt(sTo)) {
                    return {
                        kind: BLOCKS.OP.RANDOM,
                        low: nFrom <= nTo ? from : to,
                        high: nFrom <= nTo ? to : from,
                        useInts: true,
                        useFloats: false
                    };
                }
                // Otherwise hint that these are floats
                return {
                    kind: BLOCKS.OP.RANDOM,
                    low: nFrom <= nTo ? from : to,
                    high: nFrom <= nTo ? to : from,
                    useInts: false,
                    useFloats: true
                };
            } else if (from.kind === BLOCKS.CONSTANT) {
                // If only one value is known at compile-time, we can still attempt some optimizations.
                if (!Cast.isInt(Cast.toNumber(from.value))) {
                    return {
                        kind: BLOCKS.OP.RANDOM,
                        low: from,
                        high: to,
                        useInts: false,
                        useFloats: true
                    };
                }
            } else if (to.kind === BLOCKS.CONSTANT) {
                if (!Cast.isInt(Cast.toNumber(to.value))) {
                    return {
                        kind: BLOCKS.OP.RANDOM,
                        low: from,
                        high: to,
                        useInts: false,
                        useFloats: true
                    };
                }
            }
            // No optimizations possible
            return {
                kind: BLOCKS.OP.RANDOM,
                low: from,
                high: to,
                useInts: false,
                useFloats: false
            };
        }
        case 'operator_round':
            return {
                kind: BLOCKS.OP.ROUND,
                value: this.descendInputOfBlock(block, 'NUM')
            };
        case 'operator_subtract':
            return {
                kind: BLOCKS.OP.SUBTRACT,
                left: this.descendInputOfBlock(block, 'NUM1'),
                right: this.descendInputOfBlock(block, 'NUM2')
            };

        case 'procedures_call':
            return this.descendProcedure(block);

        case 'sensing_answer':
            return {
                kind: BLOCKS.SENSING.ANSWER
            };
        case 'sensing_coloristouchingcolor':
            return {
                kind: BLOCKS.SENSING.COLOR_TOUCHING_COLOR,
                target: this.descendInputOfBlock(block, 'COLOR2'),
                mask: this.descendInputOfBlock(block, 'COLOR')
            };
        case 'sensing_current':
            switch (block.fields.CURRENTMENU.value.toLowerCase()) {
            case 'year':
                return {
                    kind: BLOCKS.SENSING.YEAR
                };
            case 'month':
                return {
                    kind: BLOCKS.SENSING.MONTH
                };
            case 'date':
                return {
                    kind: BLOCKS.SENSING.DATE
                };
            case 'dayofweek':
                return {
                    kind: BLOCKS.SENSING.DAYOFWEEK
                };
            case 'hour':
                return {
                    kind: BLOCKS.SENSING.HOUR
                };
            case 'minute':
                return {
                    kind: BLOCKS.SENSING.MINUTE
                };
            case 'second':
                return {
                    kind: BLOCKS.SENSING.SECOND
                };
            case 'refreshtime':
                return {
                    kind: BLOCKS.SENSING.REFRESH_TIME
                };
            }
            return {
                kind: BLOCKS.CONSTANT,
                value: 0
            };
        case 'sensing_dayssince2000':
            return {
                kind: BLOCKS.SENSING.DAYS_SINCE_2000
            };
        case 'sensing_distanceto':
            return {
                kind: BLOCKS.SENSING.DISTANCE,
                target: this.descendInputOfBlock(block, 'DISTANCETOMENU')
            };
        case 'sensing_keypressed':
            return {
                kind: BLOCKS.KEYBOARD.PRESSED,
                key: this.descendInputOfBlock(block, 'KEY_OPTION')
            };
        case 'sensing_mousedown':
            return {
                kind: BLOCKS.MOUSE.DOWN
            };
        case 'sensing_mousex':
            return {
                kind: BLOCKS.MOUSE.X
            };
        case 'sensing_mousey':
            return {
                kind: BLOCKS.MOUSE.Y
            };
        case 'sensing_of':
            return {
                kind: BLOCKS.SENSING.OF,
                property: block.fields.PROPERTY.value,
                object: this.descendInputOfBlock(block, 'OBJECT')
            };
        case 'sensing_timer':
            this.usesTimer = true;
            return {
                kind: BLOCKS.TIMER.GET
            };
        case 'sensing_touchingcolor':
            return {
                kind: BLOCKS.SENSING.TOUCHING_COLOR,
                color: this.descendInputOfBlock(block, 'COLOR')
            };
        case 'sensing_touchingobject':
            return {
                kind: BLOCKS.SENSING.TOUCHING,
                object: this.descendInputOfBlock(block, 'TOUCHINGOBJECTMENU')
            };
        case 'sensing_online':
            return {
                kind: BLOCKS.SENSING.ONLINE
            };
        case 'sensing_username':
            return {
                kind: BLOCKS.SENSING.USERNAME
            };

        case 'sound_sounds_menu':
            // This menu is special compared to other menus -- it actually has an opcode function.
            return {
                kind: BLOCKS.CONSTANT,
                value: block.fields.SOUND_MENU.value
            };

        case 'tw_getLastKeyPressed':
            return {
                kind: BLOCKS.TW.LAST_KEY_PRESSED
            };

        default: {
            const opcodeFunction = this.runtime.getOpcodeFunction(block.opcode);
            if (opcodeFunction) {
                // It might be a non-compiled primitive from a standard category
                if (compatBlocks.inputs.includes(block.opcode)) {
                    return this.descendCompatLayer(block);
                }
                // It might be an extension block.
                const blockInfo = this.getBlockInfo(block.opcode);
                if (blockInfo) {
                    const type = blockInfo.info.blockType;
                    if (type === BlockType.REPORTER || type === BlockType.BOOLEAN) {
                        return this.descendCompatLayer(block);
                    }
                }
            }

            // It might be a menu.
            const inputs = Object.keys(block.inputs);
            const fields = Object.keys(block.fields);
            if (inputs.length === 0 && fields.length === 1) {
                return {
                    kind: BLOCKS.CONSTANT,
                    value: block.fields[fields[0]].value
                };
            }

            log.warn(`IR: Unknown input: ${block.opcode}`, block);
            throw new Error(`IR: Unknown input: ${block.opcode}`);
        }
        }
    }

    /**
     * Descend into a stacked block. (eg. "move ( ) steps")
     * @param {*} block The Scratch block to parse.
     * @private
     * @returns {node} Compiled node for this block.
     */
    descendStackedBlock (block) {
        switch (block.opcode) {
        case 'control_all_at_once':
            // In Scratch 3, this block behaves like "if 1 = 1"
            return {
                kind: BLOCKS.CONTROL.IF,
                condition: {
                    kind: BLOCKS.CONSTANT,
                    value: true
                },
                whenTrue: this.descendSubstack(block, 'SUBSTACK'),
                whenFalse: []
            };
        case 'control_clear_counter':
            return {
                kind: BLOCKS.COUNTER.CLEAR
            };
        case 'control_create_clone_of':
            return {
                kind: BLOCKS.CONTROL.CREATE_CLONE,
                target: this.descendInputOfBlock(block, 'CLONE_OPTION')
            };
        case 'control_delete_this_clone':
            this.script.yields = true;
            return {
                kind: BLOCKS.CONTROL.DELETE_CLONE
            };
        case 'control_forever':
            this.analyzeLoop();
            return {
                kind: BLOCKS.CONTROL.WHILE,
                condition: {
                    kind: BLOCKS.CONSTANT,
                    value: true
                },
                do: this.descendSubstack(block, 'SUBSTACK')
            };
        case 'control_for_each':
            this.analyzeLoop();
            return {
                kind: BLOCKS.CONTROL.FOR,
                variable: this.descendVariable(block, 'VARIABLE', SCALAR_TYPE),
                count: this.descendInputOfBlock(block, 'VALUE'),
                do: this.descendSubstack(block, 'SUBSTACK')
            };
        case 'control_if':
            return {
                kind: BLOCKS.CONTROL.IF,
                condition: this.descendInputOfBlock(block, 'CONDITION'),
                whenTrue: this.descendSubstack(block, 'SUBSTACK'),
                whenFalse: []
            };
        case 'control_if_else':
            return {
                kind: BLOCKS.CONTROL.IF,
                condition: this.descendInputOfBlock(block, 'CONDITION'),
                whenTrue: this.descendSubstack(block, 'SUBSTACK'),
                whenFalse: this.descendSubstack(block, 'SUBSTACK2')
            };
        case 'control_incr_counter':
            return {
                kind: BLOCKS.COUNTER.INCR
            };
        case 'control_repeat':
            this.analyzeLoop();
            return {
                kind: BLOCKS.CONTROL.REPEAT,
                times: this.descendInputOfBlock(block, 'TIMES'),
                do: this.descendSubstack(block, 'SUBSTACK')
            };
        case 'control_repeat_until': {
            this.analyzeLoop();
            // Dirty hack: automatically enable warp timer for this block if it uses timer
            // This fixes project that do things like "repeat until timer > 0.5"
            this.usesTimer = false;
            const condition = this.descendInputOfBlock(block, 'CONDITION');
            const needsWarpTimer = this.usesTimer;
            if (needsWarpTimer) {
                this.script.yields = true;
            }
            return {
                kind: BLOCKS.CONTROL.WHILE,
                condition: {
                    kind: BLOCKS.OP.NOT,
                    operand: condition
                },
                do: this.descendSubstack(block, 'SUBSTACK'),
                warpTimer: needsWarpTimer
            };
        }
        case 'control_stop': {
            const level = block.fields.STOP_OPTION.value;
            if (level === 'all') {
                this.script.yields = true;
                return {
                    kind: BLOCKS.CONTROL.STOP_ALL
                };
            } else if (level === 'other scripts in sprite' || level === 'other scripts in stage') {
                return {
                    kind: BLOCKS.CONTROL.STOP_OTHERS
                };
            } else if (level === 'this script') {
                return {
                    kind: BLOCKS.CONTROL.STOP_SCRIPT
                };
            }
            return {
                kind: BLOCKS.NOOP
            };
        }
        case 'control_wait':
            this.script.yields = true;
            return {
                kind: BLOCKS.CONTROL.WAIT,
                seconds: this.descendInputOfBlock(block, 'DURATION')
            };
        case 'control_wait_until':
            this.script.yields = true;
            return {
                kind: BLOCKS.CONTROL.WAIT_UNTIL,
                condition: this.descendInputOfBlock(block, 'CONDITION')
            };
        case 'control_while':
            this.analyzeLoop();
            return {
                kind: BLOCKS.CONTROL.WHILE,
                condition: this.descendInputOfBlock(block, 'CONDITION'),
                do: this.descendSubstack(block, 'SUBSTACK'),
                // We should consider analyzing this like we do for control_repeat_until
                warpTimer: false
            };
        case 'control_switch':
            return {
                kind: BLOCKS.CONTROL.SWITCH,
                value: this.descendInputOfBlock(block, 'VALUE'),
                do: this.descendSubstack(block, 'SUBSTACK')
            };
        case 'control_case':
            return {
                kind: BLOCKS.CONTROL.CASE,
                value: this.descendInputOfBlock(block, 'VALUE'),
                do: this.descendSubstack(block, 'SUBSTACK')
            };
        case 'control_default':
            return {
                kind: BLOCKS.CONTROL.DEFAULT,
                do: this.descendSubstack(block, 'SUBSTACK')
            };
        case 'control_break':
            return {
                kind: BLOCKS.CONTROL.BREAK
            };
        case 'control_case_fallthrough':
            return {
                kind: BLOCKS.CONTROL.CASE_FALLTHROUGH,
                value: this.descendInputOfBlock(block, 'VALUE')
            };

        case 'data_addtolist':
            return {
                kind: BLOCKS.LIST.ADD,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                item: this.descendInputOfBlock(block, 'ITEM')
            };
        case 'data_set_list_to_array':
            return {
                kind: BLOCKS.LIST.SET_ARRAY,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                array: this.descendInputOfBlock(block, 'ARRAY')
            };
        case 'data_changevariableby': {
            const variable = this.descendVariable(block, 'VARIABLE', SCALAR_TYPE);
            return {
                kind: BLOCKS.VAR.SET,
                variable,
                value: {
                    kind: BLOCKS.OP.ADD,
                    left: {
                        kind: BLOCKS.VAR.GET,
                        variable
                    },
                    right: this.descendInputOfBlock(block, 'VALUE')
                }
            };
        }
        case 'data_deletealloflist':
            return {
                kind: BLOCKS.LIST.DELETE_ALL,
                list: this.descendVariable(block, 'LIST', LIST_TYPE)
            };
        case 'data_deleteoflist': {
            const index = this.descendInputOfBlock(block, 'INDEX');
            if (index.kind === BLOCKS.CONSTANT && index.value === 'all') {
                return {
                    kind: BLOCKS.LIST.DELETE_ALL,
                    list: this.descendVariable(block, 'LIST', LIST_TYPE)
                };
            }
            return {
                kind: BLOCKS.LIST.DELETE,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                index: index
            };
        }
        case 'data_hidelist':
            return {
                kind: BLOCKS.LIST.HIDE,
                list: this.descendVariable(block, 'LIST', LIST_TYPE)
            };
        case 'data_hidevariable':
            return {
                kind: BLOCKS.VAR.HIDE,
                variable: this.descendVariable(block, 'VARIABLE', SCALAR_TYPE)
            };
        case 'data_insertatlist':
            return {
                kind: BLOCKS.LIST.INSERT,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                index: this.descendInputOfBlock(block, 'INDEX'),
                item: this.descendInputOfBlock(block, 'ITEM')
            };
        case 'data_replaceitemoflist':
            return {
                kind: BLOCKS.LIST.REPLACE,
                list: this.descendVariable(block, 'LIST', LIST_TYPE),
                index: this.descendInputOfBlock(block, 'INDEX'),
                item: this.descendInputOfBlock(block, 'ITEM')
            };
        case 'data_setvariableto':
            return {
                kind: BLOCKS.VAR.SET,
                variable: this.descendVariable(block, 'VARIABLE', SCALAR_TYPE),
                value: this.descendInputOfBlock(block, 'VALUE')
            };
        case 'data_showlist':
            return {
                kind: BLOCKS.LIST.SHOW,
                list: this.descendVariable(block, 'LIST', LIST_TYPE)
            };
        case 'data_showvariable':
            return {
                kind: BLOCKS.VAR.SHOW,
                variable: this.descendVariable(block, 'VARIABLE', SCALAR_TYPE)
            };

        case 'event_broadcast':
            return {
                kind: BLOCKS.EVENT.BROADCAST,
                broadcast: this.descendInputOfBlock(block, 'BROADCAST_INPUT')
            };
        case 'event_broadcastandwait':
            this.script.yields = true;
            return {
                kind: BLOCKS.EVENT.BROADCAST_AND_WAIT,
                broadcast: this.descendInputOfBlock(block, 'BROADCAST_INPUT')
            };

        case 'looks_changeeffectby':
            return {
                kind: BLOCKS.LOOKS.CHANGE_EFFECT,
                effect: block.fields.EFFECT.value.toLowerCase(),
                value: this.descendInputOfBlock(block, 'CHANGE')
            };
        case 'looks_changesizeby':
            return {
                kind: BLOCKS.LOOKS.CHANGE_SIZE,
                size: this.descendInputOfBlock(block, 'CHANGE')
            };
        case 'looks_cleargraphiceffects':
            return {
                kind: BLOCKS.LOOKS.CLEAR_EFFECTS
            };
        case 'looks_goforwardbackwardlayers':
            if (block.fields.FORWARD_BACKWARD.value === 'forward') {
                return {
                    kind: BLOCKS.LOOKS.FORWARD_LAYERS,
                    layers: this.descendInputOfBlock(block, 'NUM')
                };
            }
            return {
                kind: BLOCKS.LOOKS.BACKWARD_LAYERS,
                layers: this.descendInputOfBlock(block, 'NUM')
            };
        case 'looks_gotofrontback':
            if (block.fields.FRONT_BACK.value === 'front') {
                return {
                    kind: BLOCKS.LOOKS.GOTO_FRONT
                };
            }
            return {
                kind: BLOCKS.LOOKS.GOTO_BACK
            };
        case 'looks_hide':
            return {
                kind: BLOCKS.LOOKS.HIDE
            };
        case 'looks_nextbackdrop':
            return {
                kind: BLOCKS.LOOKS.NEXT_BACKDROP
            };
        case 'looks_nextcostume':
            return {
                kind: BLOCKS.LOOKS.NEXT_COSTUME
            };
        case 'looks_say':
            return {
                kind: BLOCKS.LOOKS.SAY,
                message: this.descendInputOfBlock(block, 'MESSAGE')
            };
        case 'looks_seteffectto':
            return {
                kind: BLOCKS.LOOKS.SET_EFFECT,
                effect: block.fields.EFFECT.value.toLowerCase(),
                value: this.descendInputOfBlock(block, 'VALUE')
            };
        case 'looks_setsizeto':
            return {
                kind: BLOCKS.LOOKS.SET_SIZE,
                size: this.descendInputOfBlock(block, 'SIZE')
            };
        case 'looks_show':
            return {
                kind: BLOCKS.LOOKS.SHOW
            };
        case 'looks_switchbackdropto':
            return {
                kind: BLOCKS.LOOKS.SWITCH_BACKDROP,
                backdrop: this.descendInputOfBlock(block, 'BACKDROP')
            };
        case 'looks_switchcostumeto':
            return {
                kind: BLOCKS.LOOKS.SWITCH_COSTUME,
                costume: this.descendInputOfBlock(block, 'COSTUME')
            };
        case 'looks_think':
            return {
                kind: BLOCKS.LOOKS.THINK,
                message: this.descendInputOfBlock(block, 'MESSAGE')
            };

        case 'motion_changexby':
            return {
                kind: BLOCKS.MOTION.CHANGE_X,
                dx: this.descendInputOfBlock(block, 'DX')
            };
        case 'motion_changeyby':
            return {
                kind: BLOCKS.MOTION.CHANGE_Y,
                dy: this.descendInputOfBlock(block, 'DY')
            };
        case 'motion_gotoxy':
            return {
                kind: BLOCKS.MOTION.SET_XY,
                x: this.descendInputOfBlock(block, 'X'),
                y: this.descendInputOfBlock(block, 'Y')
            };
        case 'motion_ifonedgebounce':
            return {
                kind: BLOCKS.MOTION.IF_ON_EDGE_BOUNCE
            };
        case 'motion_movesteps':
            return {
                kind: BLOCKS.MOTION.STEP,
                steps: this.descendInputOfBlock(block, 'STEPS')
            };
        case 'motion_pointindirection':
            return {
                kind: BLOCKS.MOTION.SET_DIRECTION,
                direction: this.descendInputOfBlock(block, 'DIRECTION')
            };
        case 'motion_pointtowards_xy':
            return {
                kind: BLOCKS.MOTION.POINT_TOWARDS_XY,
                x: this.descendInputOfBlock(block, 'X'),
                y: this.descendInputOfBlock(block, 'Y')
            };
        case 'motion_pointtowards_xyfrom':
            return {
                kind: BLOCKS.MOTION.POINT_TOWARDS_XY_FROM,
                x: this.descendInputOfBlock(block, 'X'),
                y: this.descendInputOfBlock(block, 'Y'),
                fromx: this.descendInputOfBlock(block, 'FROMX'),
                fromy: this.descendInputOfBlock(block, 'FROMY')
            };
        case 'motion_setrotationstyle':
            return {
                kind: BLOCKS.MOTION.SET_ROTATION_STYLE,
                style: block.fields.STYLE.value
            };
        case 'motion_setx':
            return {
                kind: BLOCKS.MOTION.SET_X,
                x: this.descendInputOfBlock(block, 'X')
            };
        case 'motion_sety':
            return {
                kind: BLOCKS.MOTION.SET_Y,
                y: this.descendInputOfBlock(block, 'Y')
            };
        case 'motion_turnleft':
            return {
                kind: BLOCKS.MOTION.SET_DIRECTION,
                direction: {
                    kind: BLOCKS.OP.SUBTRACT,
                    left: {
                        kind: BLOCKS.MOTION.DIRECTION
                    },
                    right: this.descendInputOfBlock(block, 'DEGREES')
                }
            };
        case 'motion_turnright':
            return {
                kind: BLOCKS.MOTION.SET_DIRECTION,
                direction: {
                    kind: BLOCKS.OP.ADD,
                    left: {
                        kind: BLOCKS.MOTION.DIRECTION
                    },
                    right: this.descendInputOfBlock(block, 'DEGREES')
                }
            };

        case 'pen_clear':
            return {
                kind: BLOCKS.PEN.CLEAR
            };
        case 'pen_changePenColorParamBy':
            return {
                kind: BLOCKS.PEN.CHANGE_PARAM,
                param: this.descendInputOfBlock(block, 'COLOR_PARAM'),
                value: this.descendInputOfBlock(block, 'VALUE')
            };
        case 'pen_changePenHueBy':
            return {
                kind: BLOCKS.PEN.LEGACY_CHANGE_HUE,
                hue: this.descendInputOfBlock(block, 'HUE')
            };
        case 'pen_changePenShadeBy':
            return {
                kind: BLOCKS.PEN.LEGACY_CHANGE_SHADE,
                shade: this.descendInputOfBlock(block, 'SHADE')
            };
        case 'pen_penDown':
            return {
                kind: BLOCKS.PEN.DOWN
            };
        case 'pen_penUp':
            return {
                kind: BLOCKS.PEN.UP
            };
        case 'pen_setPenColorParamTo':
            return {
                kind: BLOCKS.PEN.SET_PARAM,
                param: this.descendInputOfBlock(block, 'COLOR_PARAM'),
                value: this.descendInputOfBlock(block, 'VALUE')
            };
        case 'pen_setPenColorToColor':
            return {
                kind: BLOCKS.PEN.SET_COLOR,
                color: this.descendInputOfBlock(block, 'COLOR')
            };
        case 'pen_setPenHueToNumber':
            return {
                kind: BLOCKS.PEN.LEGACY_SET_HUE,
                hue: this.descendInputOfBlock(block, 'HUE')
            };
        case 'pen_setPenShadeToNumber':
            return {
                kind: BLOCKS.PEN.LEGACY_SET_SHADE,
                shade: this.descendInputOfBlock(block, 'SHADE')
            };
        case 'pen_setPenSizeTo':
            return {
                kind: BLOCKS.PEN.SET_SIZE,
                size: this.descendInputOfBlock(block, 'SIZE')
            };
        case 'pen_changePenSizeBy':
            return {
                kind: BLOCKS.PEN.CHANGE_SIZE,
                size: this.descendInputOfBlock(block, 'SIZE')
            };
        case 'pen_stamp':
            return {
                kind: BLOCKS.PEN.STAMP
            };
        case 'pen_printText':
            return {
                kind: BLOCKS.PEN.PRINT_TEXT,
                text: this.descendInputOfBlock(block, 'TEXT'),
                x: this.descendInputOfBlock(block, 'X'),
                y: this.descendInputOfBlock(block, 'Y')
            };
        case 'pen_drawTriangle':
            return {
                kind: BLOCKS.PEN.DRAW_TRIANGLE,
                x0: this.descendInputOfBlock(block, 'X0'),
                y0: this.descendInputOfBlock(block, 'Y0'),
                x1: this.descendInputOfBlock(block, 'X1'),
                y1: this.descendInputOfBlock(block, 'Y1'),
                x2: this.descendInputOfBlock(block, 'X2'),
                y2: this.descendInputOfBlock(block, 'Y2')
            };

        case 'procedures_call': {
            const procedureCode = block.mutation.proccode;
            if (block.mutation.return) {
                const visualReport = this.descendVisualReport(block);
                if (visualReport) {
                    return visualReport;
                }
            }
            if (procedureCode === 'tw:debugger;') {
                return {
                    kind: BLOCKS.TW.DEBUGGER
                };
            }
            return this.descendProcedure(block);
        }
        case 'procedures_return':
            return {
                kind: BLOCKS.PROCEDURES.RETURN,
                value: this.descendInputOfBlock(block, 'VALUE')
            };

        case 'sensing_resettimer':
            return {
                kind: BLOCKS.TIMER.RESET
            };

        default: {
            const opcodeFunction = this.runtime.getOpcodeFunction(block.opcode);
            if (opcodeFunction) {
                // It might be a non-compiled primitive from a standard category
                if (compatBlocks.stacked.includes(block.opcode)) {
                    return this.descendCompatLayer(block);
                }
                // It might be an extension block.
                const blockInfo = this.getBlockInfo(block.opcode);
                if (blockInfo) {
                    const type = blockInfo.info.blockType;
                    if (type === BlockType.COMMAND || type === BlockType.CONDITIONAL || type === BlockType.LOOP) {
                        return this.descendCompatLayer(block);
                    }
                }
            }

            const asVisualReport = this.descendVisualReport(block);
            if (asVisualReport) {
                return asVisualReport;
            }

            log.warn(`IR: Unknown stacked block: ${block.opcode}`, block);
            throw new Error(`IR: Unknown stacked block: ${block.opcode}`);
        }
        }
    }

    /**
     * Descend into a stack of blocks (eg. the blocks contained within an "if" block)
     * @param {*} parentBlock The parent Scratch block that contains the stack to parse.
     * @param {*} substackName The name of the stack to descend into.
     * @private
     * @returns {node[]} List of stacked block nodes.
     */
    descendSubstack (parentBlock, substackName) {
        const input = parentBlock.inputs[substackName];
        if (!input) {
            return [];
        }
        const stackId = input.block;
        return this.walkStack(stackId);
    }

    /**
     * Descend into and walk the siblings of a stack.
     * @param {string} startingBlockId The ID of the first block of a stack.
     * @private
     * @returns {node[]} List of stacked block nodes.
     */
    walkStack (startingBlockId) {
        const result = [];
        let blockId = startingBlockId;

        while (blockId !== null) {
            const block = this.getBlockById(blockId);
            if (!block) {
                break;
            }

            const node = this.descendStackedBlock(block);
            result.push(node);

            blockId = block.next;
        }

        return result;
    }

    /**
     * Descend into a variable.
     * @param {*} block The block that has the variable.
     * @param {string} fieldName The name of the field that the variable is stored in.
     * @param {''|'list'} type Variable type, '' for scalar and 'list' for list.
     * @private
     * @returns {*} A parsed variable object.
     */
    descendVariable (block, fieldName, type) {
        const variable = block.fields[fieldName];
        const id = variable.id;

        if (Object.prototype.hasOwnProperty.call(this.variableCache, id)) {
            return this.variableCache[id];
        }

        const data = this._descendVariable(id, variable.value, type);
        this.variableCache[id] = data;
        return data;
    }

    /**
     * @param {string} id The ID of the variable.
     * @param {string} name The name of the variable.
     * @param {''|'list'} type The variable type.
     * @private
     * @returns {*} A parsed variable object.
     */
    _descendVariable (id, name, type) {
        const target = this.target;
        const stage = this.stage;

        // Look for by ID in target...
        if (Object.prototype.hasOwnProperty.call(target.variables, id)) {
            return createVariableData('target', target.variables[id]);
        }

        // Look for by ID in stage...
        if (!target.isStage) {
            if (stage && Object.prototype.hasOwnProperty.call(stage.variables, id)) {
                return createVariableData('stage', stage.variables[id]);
            }
        }

        // Look for by name and type in target...
        for (const varId in target.variables) {
            if (Object.prototype.hasOwnProperty.call(target.variables, varId)) {
                const currVar = target.variables[varId];
                if (currVar.name === name && currVar.type === type) {
                    return createVariableData('target', currVar);
                }
            }
        }

        // Look for by name and type in stage...
        if (!target.isStage && stage) {
            for (const varId in stage.variables) {
                if (Object.prototype.hasOwnProperty.call(stage.variables, varId)) {
                    const currVar = stage.variables[varId];
                    if (currVar.name === name && currVar.type === type) {
                        return createVariableData('stage', currVar);
                    }
                }
            }
        }

        // Create it locally...
        const newVariable = new Variable(id, name, type, false);
        target.variables[id] = newVariable;

        if (target.sprite) {
            // Create the variable in all instances of this sprite.
            // This is necessary because the script cache is shared between clones.
            // sprite.clones has all instances of this sprite including the original and all clones
            for (const clone of target.sprite.clones) {
                if (!Object.prototype.hasOwnProperty.call(clone.variables, id)) {
                    clone.variables[id] = new Variable(id, name, type, false);
                }
            }
        }

        return createVariableData('target', newVariable);
    }

    /**
     * Descend into a procedure call block.
     * @param {*} block The procedure call block to parse.
     * @private
     * @returns {node} The parsed procedure call node.
     */
    descendProcedure (block) {
        const procedureCode = block.mutation.proccode;
        const paramNamesIdsAndDefaults = this.blocks.getProcedureParamNamesIdsAndDefaults(procedureCode);
        if (paramNamesIdsAndDefaults === null) {
            return {
                kind: BLOCKS.NOOP
            };
        }

        const [paramNames, paramIds, paramDefaults] = paramNamesIdsAndDefaults;

        const addonBlock = this.runtime.getAddonBlock(procedureCode);
        if (addonBlock) {
            this.script.yields = true;
            const args = Object.create(null);
            for (let i = 0; i < paramIds.length; i++) {
                let value;
                if (block.inputs[paramIds[i]] && block.inputs[paramIds[i]].block) {
                    value = this.descendInputOfBlock(block, paramIds[i]);
                } else {
                    value = {
                        kind: BLOCKS.CONSTANT,
                        value: paramDefaults[i]
                    };
                }
                args[paramNames[i]] = value;
            }
            return {
                kind: BLOCKS.ADDONS.CALL,
                code: block.code || procedureCode,
                arguments: args,
                blockId: block.id
            };
        }

        const definitionId = this.blocks.getProcedureDefinition(procedureCode);
        const definitionBlock = this.blocks.getBlock(definitionId);
        if (!definitionBlock) {
            return {
                kind: BLOCKS.NOOP
            };
        }
        const innerDefinition = this.blocks.getBlock(definitionBlock.inputs.custom_block.block);

        let isWarp = this.script.isWarp;
        if (!isWarp) {
            if (innerDefinition && innerDefinition.mutation) {
                const warp = innerDefinition.mutation.warp;
                if (typeof warp === 'boolean') {
                    isWarp = warp;
                } else if (typeof warp === 'string') {
                    isWarp = JSON.parse(warp);
                }
            }
        }

        const variant = generateProcedureVariant(procedureCode, isWarp);

        if (!this.script.dependedProcedures.includes(variant)) {
            this.script.dependedProcedures.push(variant);
        }

        // Non-warp direct recursion yields.
        if (!this.script.isWarp) {
            if (procedureCode === this.script.procedureCode) {
                this.script.yields = true;
            }
        }

        const args = [];
        for (let i = 0; i < paramIds.length; i++) {
            let value;
            if (block.inputs[paramIds[i]] && block.inputs[paramIds[i]].block) {
                value = this.descendInputOfBlock(block, paramIds[i]);
            } else {
                value = {
                    kind: BLOCKS.CONSTANT,
                    value: paramDefaults[i]
                };
            }
            args.push(value);
        }

        return {
            kind: BLOCKS.PROCEDURES.CALL,
            code: procedureCode,
            variant,
            arguments: args
        };
    }

    /**
     * Descend into a block that uses the compatibility layer.
     * @param {*} block The block to use the compatibility layer for.
     * @private
     * @returns {node} The parsed node.
     */
    descendCompatLayer (block) {
        this.script.yields = true;

        const inputs = Object.create(null);
        for (const name of Object.keys(block.inputs)) {
            if (!name.startsWith('SUBSTACK')) {
                inputs[name] = this.descendInputOfBlock(block, name);
            }
        }

        const fields = Object.create(null);
        for (const name of Object.keys(block.fields)) {
            fields[name] = block.fields[name].value;
        }

        const blockInfo = this.getBlockInfo(block.opcode);
        const blockType = (blockInfo && blockInfo.info && blockInfo.info.blockType) || BlockType.COMMAND;
        const substacks = Object.create(null);
        if (blockType === BlockType.CONDITIONAL || blockType === BlockType.LOOP) {
            for (const inputName in block.inputs) {
                if (!inputName.startsWith('SUBSTACK')) continue;
                const branchNum = inputName === 'SUBSTACK' ? 1 : +inputName.substring('SUBSTACK'.length);
                if (!isNaN(branchNum)) {
                    substacks[branchNum] = this.descendSubstack(block, inputName);
                }
            }
        }

        if (!block.code) block.code = null;

        return {
            kind: BLOCKS.COMPAT,
            id: block.id,
            opcode: block.opcode,
            blockType,
            inputs,
            fields,
            substacks,
            code: block.code
        };
    }

    analyzeLoop () {
        if (!this.script.isWarp || this.script.warpTimer) {
            this.script.yields = true;
        }
    }

    /**
     * Read the top block comment.
     * @param {string} commentId The ID of the comment to read.
     * @private
     * @returns {void}
     */
    readTopBlockComment (commentId) {
        const comment = this.target.comments[commentId];
        if (!comment) {
            // can't find the comment
            // this is safe to ignore
            return;
        }

        const text = comment.text;

        for (const line of text.split('\n')) {
            if (!/^tw\b/.test(line)) {
                continue;
            }

            const flags = line.split(' ');
            for (const flag of flags) {
                switch (flag) {
                case 'nocompile':
                    throw new Error('Script explicitly disables compilation');
                case 'stuck':
                    this.script.warpTimer = true;
                    break;
                }
            }

            // Only the first 'tw' line is parsed.
            break;
        }
    }

    /**
     * Descend into a visual report block.
     * @param {node} block The visual report block to parse.
     * @private
     * @returns {node|null} The parsed visual report node, or null if the block should be removed.
     */
    descendVisualReport (block) {
        if (!this.thread.stackClick || block.next) {
            return null;
        }
        try {
            return {
                kind: BLOCKS.VISUAL_REPORT,
                input: this.descendInput(block)
            };
        } catch (e) {
            return null;
        }
    }

    /**
     * @param {node} hatBlock
     */
    walkHat (hatBlock) {
        const nextBlock = hatBlock.next;
        const opcode = hatBlock.opcode;
        const hatInfo = this.runtime._hats[opcode];

        if (this.thread.stackClick) {
            // We still need to treat the hat as a normal block (so executableHat should be false) for
            // interpreter parity, but the reuslt is ignored.
            const opcodeFunction = this.runtime.getOpcodeFunction(opcode);
            if (opcodeFunction) {
                return [
                    this.descendCompatLayer(hatBlock),
                    ...this.walkStack(nextBlock)
                ];
            }
            return this.walkStack(nextBlock);
        }

        if (hatInfo.edgeActivated) {
            // Edge-activated HAT
            this.script.yields = true;
            this.script.executableHat = true;
            return [
                {
                    kind: BLOCKS.HAT.EDGE,
                    id: hatBlock.id,
                    condition: this.descendCompatLayer(hatBlock)
                },
                ...this.walkStack(nextBlock)
            ];
        }

        const opcodeFunction = this.runtime.getOpcodeFunction(opcode);
        if (opcodeFunction) {
            // Predicate-based HAT
            this.script.yields = true;
            this.script.executableHat = true;
            return [
                {
                    kind: BLOCKS.HAT.PREDICATE,
                    condition: this.descendCompatLayer(hatBlock)
                },
                ...this.walkStack(nextBlock)
            ];
        }

        return this.walkStack(nextBlock);
    }

    /**
     * @param {string} topBlockId The ID of the top block of the script.
     * @returns {IntermediateScript}
     */
    generate (topBlockId) {
        this.blocks.populateProcedureCache();

        this.script.topBlockId = topBlockId;

        const topBlock = this.getBlockById(topBlockId);
        if (!topBlock) {
            if (this.script.isProcedure) {
                // Empty procedure
                return this.script;
            }
            throw new Error('Cannot find top block');
        }

        if (topBlock.comment) {
            this.readTopBlockComment(topBlock.comment);
        }

        // We do need to evaluate empty hats
        const hatInfo = this.runtime._hats[topBlock.opcode];
        const isHat = !!hatInfo;
        if (isHat) {
            this.script.stack = this.walkHat(topBlock);
        } else {
            // We don't evaluate the procedures_definition top block as it never does anything
            // We also don't want it to be treated like a hat block
            let entryBlock;
            if (topBlock.opcode === 'procedures_definition') {
                entryBlock = topBlock.next;
            } else {
                entryBlock = topBlockId;
            }

            if (entryBlock) {
                this.script.stack = this.walkStack(entryBlock);
            }
        }

        return this.script;
    }
}

class IRGenerator {
    /**
     * @param {Thread} thread The thread to generate IR for.
     */
    constructor (thread) {
        this.thread = thread;
        this.blocks = thread.blockContainer;

        this.proceduresToCompile = new Map();
        this.compilingProcedures = new Map();
        /** @type {Object.<string, IntermediateScript>} */
        this.procedures = {};

        /** A list of procedure ids that have been analyzed.
         * @type {string[]}
         */
        this.analyzedProcedures = [];
    }

    /**
     * Add dependencies for a procedure.
     * @param {string[]} dependencies The dependencies to add.
     * @returns {void}
     */
    addProcedureDependencies (dependencies) {
        for (const procedureVariant of dependencies) {
            if (Object.prototype.hasOwnProperty.call(this.procedures, procedureVariant)) {
                continue;
            }
            if (this.compilingProcedures.has(procedureVariant)) {
                continue;
            }
            if (this.proceduresToCompile.has(procedureVariant)) {
                continue;
            }
            const procedureCode = parseProcedureCode(procedureVariant);
            const definition = this.blocks.getProcedureDefinition(procedureCode);
            this.proceduresToCompile.set(procedureVariant, definition);
        }
    }

    /**
     * @param {ScriptTreeGenerator} generator The generator to run.
     * @param {string} topBlockId The ID of the top block in the stack.
     * @returns {IntermediateScript} Intermediate script.
     */
    generateScriptTree (generator, topBlockId) {
        const result = generator.generate(topBlockId);
        this.addProcedureDependencies(result.dependedProcedures);
        return result;
    }

    /**
     * Recursively analyze a script and its dependencies.
     * @param {IntermediateScript} script Intermediate script.
     */
    analyzeScript (script) {
        let madeChanges = false;
        for (const procedureCode of script.dependedProcedures) {
            const procedureData = this.procedures[procedureCode];

            // Analyze newly found procedures.
            if (!this.analyzedProcedures.includes(procedureCode)) {
                this.analyzedProcedures.push(procedureCode);
                if (this.analyzeScript(procedureData)) {
                    madeChanges = true;
                }
                this.analyzedProcedures.pop();
            }

            // If a procedure used by a script may yield, the script itself may yield.
            if (procedureData.yields && !script.yields) {
                script.yields = true;
                madeChanges = true;
            }
        }
        return madeChanges;
    }

    /**
     * @returns {IntermediateRepresentation} Intermediate representation.
     */
    generate () {
        const entry = this.generateScriptTree(new ScriptTreeGenerator(this.thread), this.thread.topBlock);

        // Compile any required procedures.
        // As procedures can depend on other procedures, this process may take several iterations.
        const procedureTreeCache = this.blocks._cache.compiledProcedures;
        while (this.proceduresToCompile.size > 0) {
            this.compilingProcedures = this.proceduresToCompile;
            this.proceduresToCompile = new Map();

            for (const [procedureVariant, definitionId] of this.compilingProcedures.entries()) {
                if (procedureTreeCache[procedureVariant]) {
                    const result = procedureTreeCache[procedureVariant];
                    this.procedures[procedureVariant] = result;
                    this.addProcedureDependencies(result.dependedProcedures);
                } else {
                    const isWarp = parseIsWarp(procedureVariant);
                    const generator = new ScriptTreeGenerator(this.thread);
                    generator.setProcedureVariant(procedureVariant);
                    if (isWarp) generator.enableWarp();
                    const compiledProcedure = this.generateScriptTree(generator, definitionId);
                    this.procedures[procedureVariant] = compiledProcedure;
                    procedureTreeCache[procedureVariant] = compiledProcedure;
                }
            }
        }

        while (this.analyzeScript(entry));

        this.optimizeScript(entry);
        for (const code of Object.keys(this.procedures)) {
            this.optimizeScript(this.procedures[code]);
        }

        const ir = new IntermediateRepresentation(entry);
        ir.procedures = this.procedures;
        return ir;
    }

    /**
     * Optimize a script.
     * @param {*} script The script to optimize.
     * @private
     * @returns {*} The optimized script.
     */
    optimizeScript (script) {
        /**
         * @param {node[]} nodes The nodes to optimize.
         * @returns {node[]} The optimized nodes.
         */
        const optimizeStack = nodes => {
            if (!nodes || !nodes.length) return [];
            const out = [];
            let prev = null;
            for (let i = 0; i < nodes.length; i++) {
                const chain = this._tryConvertEqualsIfChain(nodes, i);
                if (chain) {
                    const {converted, count} = chain;
                    for (const nn of converted) {
                        if (!this._isDuplicate(prev, nn)) {
                            out.push(nn);
                            prev = nn;
                        }
                    }
                    i += (count - 1);
                    continue;
                }
                const node = nodes[i];
                const n = this.optimizeNode(node);
                if (!n) continue;
                if (Array.isArray(n)) {
                    for (const nn of n) {
                        if (!nn) continue;
                        if (!this._isDuplicate(prev, nn)) {
                            out.push(nn);
                            prev = nn;
                        }
                    }
                    continue;
                }
                if (!this._isDuplicate(prev, n)) {
                    out.push(n);
                    prev = n;
                }
            }
            return out;
        };
        script.stack = optimizeStack(script.stack);
    }

    /**
     * Optimize a node.
     * @param {node} node The node to optimize.
     * @private
     * @returns {node|null} The optimized node, or null if the node should be removed.
     */
    optimizeNode (node) {
        if (!node) return null;
        switch (node.kind) {
        case BLOCKS.NOOP:
            return null;
        case BLOCKS.CONTROL.IF: {
            const cond = node.condition;
            if (cond && cond.kind === BLOCKS.CONSTANT) {
                const stack = cond.value ? node.whenTrue : node.whenFalse;
                node.whenTrue = this._optimizeSubstack(stack);
                node.value = true;
                return node;
            }
            node.whenTrue = this._optimizeSubstack(node.whenTrue);
            if (node.whenFalse) node.whenFalse = this._optimizeSubstack(node.whenFalse);
            return node;
        }
        case BLOCKS.CONTROL.REPEAT: {
            node.do = this._optimizeSubstack(node.do);
            return node;
        }
        case BLOCKS.CONTROL.WHILE: {
            const cond = node.condition;
            if (cond && cond.kind === BLOCKS.CONSTANT) {
                const v = !!cond.value;
                if (!v) return null;
            }
            node.do = this._optimizeSubstack(node.do);
            return node;
        }
        case BLOCKS.CONTROL.SWITCH:
        case BLOCKS.CONTROL.CASE:
        case BLOCKS.CONTROL.DEFAULT: {
            node.do = this._optimizeSubstack(node.do);
            return node;
        }
        case BLOCKS.VAR.SET: {
            node.value = this.optimizeInput(node.value);
            return node;
        }
        case BLOCKS.LIST.ADD:
        case BLOCKS.LIST.INSERT:
        case BLOCKS.LIST.REPLACE: {
            node.index = this.optimizeInput(node.index);
            node.item = this.optimizeInput(node.item);
            return node;
        }
        default:
            return this.optimizeInputs(node);
        }
    }

    /**
     * Optimize a stack.
     * @param {node[]} stack The stack to optimize.
     * @private
     * @returns {node[]} The optimized stack.
     */
    _optimizeSubstack (stack) {
        if (!stack || !stack.length) return [];
        const out = [];
        let prev = null;
        for (const node of stack) {
            const n = this.optimizeNode(node);
            if (!n) continue;
            if (Array.isArray(n)) {
                for (const nn of n) {
                    if (!nn) continue;
                    if (!this._isDuplicate(prev, nn)) {
                        out.push(nn);
                        prev = nn;
                    }
                }
            } else if (!this._isDuplicate(prev, n)) {
                out.push(n);
                prev = n;
            }
        }
        return out;
    }

    /**
     * Check if two nodes are duplicates.
     * @param {node} prev The previous node.
     * @param {node} next The next node.
     * @private
     * @returns {boolean} True if the nodes are duplicates.
     */
    _isDuplicate (prev, next) {
        if (!prev || !next) return false;
        if (prev.kind !== next.kind) return false;
        switch (next.kind) {
        case BLOCKS.LIST.DELETE_ALL:
            return prev.list && next.list && prev.list.id === next.list.id;
        case BLOCKS.LIST.SHOW:
        case BLOCKS.LIST.HIDE:
            return prev.list && next.list && prev.list.id === next.list.id;
        case BLOCKS.VAR.SHOW:
        case BLOCKS.VAR.HIDE:
            return prev.variable && next.variable && prev.variable.id === next.variable.id;
        case BLOCKS.LOOKS.CLEAR_EFFECTS:
        case BLOCKS.LOOKS.GOTO_FRONT:
        case BLOCKS.LOOKS.GOTO_BACK:
        case BLOCKS.LOOKS.SHOW:
        case BLOCKS.LOOKS.HIDE:
            return true;
        default:
            return false;
        }
    }

    /**
     * Get a unique key for a node.
     * @param {node} node The node to get a key for.
     * @private
     * @returns {string} The unique key for the node.
     */
    _nodeKey (node) {
        try {
            return JSON.stringify(node);
        } catch (_e) {
            return '';
        }
    }

    /**
     * Try to convert an equals if chain into a switch.
     * @param {node[]} nodes The nodes to convert.
     * @param {number} startIndex The index to start converting from.
     * @private
     * @returns {object|null} The converted node, or null if the conversion failed.
     */
    _tryConvertEqualsIfChain (nodes, startIndex) {
        const first = nodes[startIndex];
        if (!first || first.kind !== BLOCKS.CONTROL.IF) return null;
        const cond = first.condition;
        if (!cond || cond.kind !== BLOCKS.OP.EQUALS) return null;
        if (first.whenFalse && first.whenFalse.length) return null;
        const leftKey = this._nodeKey(cond.left);
        const cases = [];
        let i = startIndex;
        while (i < nodes.length) {
            const n = nodes[i];
            if (!n || n.kind !== BLOCKS.CONTROL.IF) break;
            const c = n.condition;
            if (!c || c.kind !== BLOCKS.OP.EQUALS) break;
            if (this._nodeKey(c.left) !== leftKey) break;
            if (!c.right || c.right.kind !== BLOCKS.CONSTANT) break;
            if (n.whenFalse && n.whenFalse.length) break;
            cases.push({value: c.right, body: this._optimizeSubstack(n.whenTrue)});
            i += 1;
        }
        if (cases.length < 2) return null;
        const switchBody = [];
        let allNumbers = true;
        for (const cs of cases) {
            const cur = cs.value;
            if (cur.kind !== BLOCKS.CONSTANT) {
                return null;
            }
            const asNum = +cur.value;
            if (Number.isNaN(asNum)) {
                allNumbers = false;
            } else {
                cur.value = asNum;
            }
            switchBody.push({
                kind: BLOCKS.CONTROL.CASE,
                value: cur,
                do: cs.body,
                useNumbers: false
            });
            const last = cs.body[cs.body.length - 1];
            if (last && (last.kind !== BLOCKS.CONTROL.BREAK && last.kind !== BLOCKS.CONTROL.STOP_SCRIPT)) {
                // we cant turn this if chain into a switch case if the code doesnt handle fallthrough
                return null;
            }
        }

        for (const cs of switchBody) {
            cs.useNumbers = allNumbers;
        }

        const switchNode = {
            kind: BLOCKS.CONTROL.SWITCH,
            value: JSON.parse(leftKey),
            do: switchBody,
            useNumbers: allNumbers
        };
        return {
            converted: [switchNode],
            count: cases.length
        };
    }

    /**
     * Optimize an input.
     * @param {node} node The input to optimize.
     * @private
     * @returns {node} The optimized input.
     */
    optimizeInput (node) {
        if (!node) return node;
        switch (node.kind) {
        case BLOCKS.OP.ADD:
        case BLOCKS.OP.SUBTRACT:
        case BLOCKS.OP.MULTIPLY:
        case BLOCKS.OP.DIVIDE:
        case BLOCKS.OP.MOD:
            return this._optimizeArithmetic(node);
        case BLOCKS.OP.LENGTH:
            return this._optimizeLength(node);
        default:
            return this.optimizeInputs(node);
        }
    }

    /**
     * Optimize the inputs of a node.
     * @param {node} node The node to optimize.
     * @private
     * @returns {node} The optimized node.
     */
    optimizeInputs (node) {
        if (!node) return node;
        for (const k of Object.keys(node)) {
            const v = node[k];
            if (v && typeof v === 'object' && v.kind) {
                node[k] = this.optimizeInput(v);
            }
        }
        return node;
    }

    /**
     * Optimize an arithmetic node.
     * @param {node} node The arithmetic node to optimize.
     * @private
     * @returns {node} The optimized arithmetic node.
     */
    _optimizeArithmetic (node) {
        const left = this.optimizeInput(node.left);
        const right = this.optimizeInput(node.right);
        node.left = left;
        node.right = right;
        if (left && right && left.kind === BLOCKS.CONSTANT && right.kind === BLOCKS.CONSTANT) {
            const a = +left.value;
            const b = +right.value;
            if (Number.isFinite(a) && Number.isFinite(b)) {
                switch (node.kind) {
                case BLOCKS.OP.ADD:
                    return {kind: BLOCKS.CONSTANT, value: (a + b).toString()};
                case BLOCKS.OP.SUBTRACT:
                    return {kind: BLOCKS.CONSTANT, value: (a - b).toString()};
                case BLOCKS.OP.MULTIPLY:
                    return {kind: BLOCKS.CONSTANT, value: (a * b).toString()};
                case BLOCKS.OP.DIVIDE:
                    return {kind: BLOCKS.CONSTANT, value: (a / b).toString()};
                case BLOCKS.OP.MOD:
                    return {kind: BLOCKS.CONSTANT, value: (a % b).toString()};
                }
            }
        }
        return node;
    }

    /**
     * Optimize a length node.
     * @param {node} node The length node to optimize.
     * @private
     * @returns {node} The optimized length node.
     */
    _optimizeLength (node) {
        const s = this.optimizeInput(node.string);
        node.string = s;
        if (s && s.kind === BLOCKS.CONSTANT) {
            return {kind: BLOCKS.CONSTANT, value: ((`${s.value}`).length).toString()};
        }
        return node;
    }
}

module.exports = {
    ScriptTreeGenerator,
    IRGenerator
};
